version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: biblioteca_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P57u9j
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Injeta a estrutura SQL de inicialização automática de tabelas
      - ./back-end/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # Verifica se o banco de dados está de fato saudável e pronto para conexões
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
