name: Biblioteca API CI Pipeline

# Dispara o pipeline em pushes ou pull requests para a branch main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Build .NET
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar .NET 10
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar Dependências
        run: dotnet restore back-end/EstanteInteligente.csproj

      - name: Compilar o Projeto
        run: dotnet build back-end/EstanteInteligente.csproj --no-restore -c Release
